name: animeca
version: 1.0.0+1
publish_to: none
description: Anime streaming video
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  google_fonts: ^6.1.0
  http: 1.1.0
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  video_player: ^2.7.2
  flick_video_player: ^0.5.0
  chewie: ^1.5.0
  carousel_slider: ^4.2.1
  google_sign_in: 6.1.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/bg_onboarding.png
    - assets/images/AOT.png
    - assets/images/images_login.png
    - assets/icons/favorite.png
    - assets/icons/home.png
    - assets/icons/menu_dot.png
    - assets/icons/search.png
    - assets/icons/user.png
    - assets/icons/saved.png
    - assets/icons/like.png
    - assets/icons/share.png
    - assets/icons/info.png
    - assets/icons/favorite_active.png
    - assets/icons/home_active.png
    - assets/icons/search_active.png
    - assets/icons/user_active.png
  uses-material-design: true

